language: php
php:
  - "5.3"
before_script:
  - "sudo chmod -R 777  ."
  - "sudo apt-get install apache2"
  - "sudo a2enmod actions"
  - "sudo a2enmod rewrite"
  - echo "export PATH=/home/vagrant/.phpenv/bin:$PATH" | sudo tee -a /etc/apache2/envvars > /dev/null
  - echo "$(curl -fsSL https://raw.github.com/gist/16d751c979fdeb5a14e3/gistfile1.txt)" | sudo tee /etc/apache2/conf.d/phpconfig > /dev/null
  - echo "$(curl -fsSL https://raw.github.com/gist/2eb301570ed4a1f4c33d/gistfile1.txt)" | sed -e "s,PATH,`pwd`,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
  - "sudo service apache2 restart"
  - mysql -u root -e "CREATE USER 'pyro'@'127.0.0.1' IDENTIFIED BY 'pyro'"
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - "firefox &"
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.26.0.jar"
  - "java -jar selenium-server-standalone-2.26.0.jar > /dev/null 2>&1 &"
  - "sleep 30"

before_install: pear channel-discover pear.phpunit.de
install: pear install phpunit/PHPUnit_Selenium
script: phpunit tests/integration/installer/TestInstallerValidDbCreds.php
branches:
  only:
    - feature/selenium

