(function(a){a("a[data-reveal-id]").live("click",function(b){b.preventDefault();b=a(this).attr("data-reveal-id");a("#"+b).reveal(a(this).data())});a.fn.reveal=function(b){b=a.extend({},{animation:"fadeAndPop",animationSpeed:300,closeOnBackgroundClick:!0,dismissModalClass:"close-reveal-modal"},b);return this.each(function(){function c(){h.unbind("click.modalEvent");a("."+b.dismissModalClass).unbind("click.modalEvent");i||(i=!0,b.animation=="fadeAndPop"&&(e.css({top:a(document).scrollTop()-j,opacity:0,
visibility:"visible"}),h.fadeIn(b.animationSpeed/2),e.delay(b.animationSpeed/2).animate({top:a(document).scrollTop()+g+"px",opacity:1},b.animationSpeed,f)),b.animation=="fade"&&(e.css({opacity:0,visibility:"visible",top:a(document).scrollTop()+g}),h.fadeIn(b.animationSpeed/2),e.delay(b.animationSpeed/2).animate({opacity:1},b.animationSpeed,f)),b.animation=="none"&&(e.css({visibility:"visible",top:a(document).scrollTop()+g}),h.css({display:"block"}),f()));e.unbind("reveal:open",c)}function d(){i||
(i=!0,b.animation=="fadeAndPop"&&(h.delay(b.animationSpeed).fadeOut(b.animationSpeed),e.animate({top:a(document).scrollTop()-j+"px",opacity:0},b.animationSpeed/2,function(){e.css({top:g,opacity:1,visibility:"hidden"});f()})),b.animation=="fade"&&(h.delay(b.animationSpeed).fadeOut(b.animationSpeed),e.animate({opacity:0},b.animationSpeed,function(){e.css({opacity:1,visibility:"hidden",top:g});f()})),b.animation=="none"&&(e.css({visibility:"hidden",top:g}),h.css({display:"none"})));e.unbind("reveal:close",
d)}function f(){i=!1}var e=a(this),g=parseInt(e.css("top")),j=e.height()+g,i=!1,h=a(".reveal-modal-bg");h.length==0&&(h=a('<div class="reveal-modal-bg" />').insertAfter(e),h.fadeTo("fast",0.8));e.bind("reveal:open",c);e.bind("reveal:close",d);e.trigger("reveal:open");a("."+b.dismissModalClass).bind("click.modalEvent",function(){e.trigger("reveal:close")});b.closeOnBackgroundClick&&(h.css({cursor:"pointer"}),h.bind("click.modalEvent",function(){e.trigger("reveal:close")}));a("body").keyup(function(a){a.which===
27&&e.trigger("reveal:close")})})}})(jQuery);
(function(a){var b={defaults:{animation:"horizontal-push",animationSpeed:600,timer:!0,advanceSpeed:4E3,pauseOnHover:!1,startClockOnMouseOut:!1,startClockOnMouseOutAfter:1E3,directionalNav:!0,captions:!0,captionAnimation:"fade",captionAnimationSpeed:600,bullets:!1,bulletThumbs:!1,bulletThumbLocation:"",afterSlideChange:a.noop,fluid:!0,centerBullets:!0},activeSlide:0,numberSlides:0,orbitWidth:null,orbitHeight:null,locked:null,timerRunning:null,degrees:0,wrapperHTML:'<div class="orbit-wrapper" />',timerHTML:'<div class="timer"><span class="mask"><span class="rotator"></span></span><span class="pause"></span></div>',
captionHTML:'<div class="orbit-caption"></div>',directionalNavHTML:'<div class="slider-nav"><span class="right">Right</span><span class="left">Left</span></div>',bulletHTML:'<ul class="orbit-bullets"></ul>',init:function(c,d){var f,b=0,g=this;this.clickTimer=a.proxy(this.clickTimer,this);this.addBullet=a.proxy(this.addBullet,this);this.resetAndUnlock=a.proxy(this.resetAndUnlock,this);this.stopClock=a.proxy(this.stopClock,this);this.startTimerAfterMouseLeave=a.proxy(this.startTimerAfterMouseLeave,
this);this.clearClockMouseLeaveTimer=a.proxy(this.clearClockMouseLeaveTimer,this);this.rotateTimer=a.proxy(this.rotateTimer,this);this.options=a.extend({},this.defaults,d);if(this.options.timer==="false")this.options.timer=!1;if(this.options.captions==="false")this.options.captions=!1;if(this.options.directionalNav==="false")this.options.directionalNav=!1;this.$element=a(c);this.$wrapper=this.$element.wrap(this.wrapperHTML).parent();this.$slides=this.$element.children("img, a, div");this.$element.bind("orbit.next",
function(){g.shift("next")});this.$element.bind("orbit.prev",function(){g.shift("prev")});this.$element.bind("orbit.goto",function(a,c){g.shift(c)});this.$element.bind("orbit.start",function(){g.startClock()});this.$element.bind("orbit.stop",function(){g.stopClock()});f=this.$slides.filter("img");f.length===0?this.loaded():f.bind("imageready",function(){b+=1;b===f.length&&g.loaded()})},loaded:function(){this.$element.addClass("orbit").css({width:"1px",height:"1px"});this.setDimentionsFromLargestSlide();
this.updateOptionsIfOnlyOneSlide();this.setupFirstSlide();this.options.timer&&(this.setupTimer(),this.startClock());this.options.captions&&this.setupCaptions();this.options.directionalNav&&this.setupDirectionalNav();this.options.bullets&&(this.setupBulletNav(),this.setActiveBullet())},currentSlide:function(){return this.$slides.eq(this.activeSlide)},setDimentionsFromLargestSlide:function(){var c=this,d;c.$element.add(c.$wrapper).width(this.$slides.first().width());c.$element.add(c.$wrapper).height(this.$slides.first().height());
c.orbitWidth=this.$slides.first().width();c.orbitHeight=this.$slides.first().height();d=this.$slides.first().clone();this.$slides.each(function(){var f=a(this),b=f.width(),f=f.height();if(b>c.$element.width())c.$element.add(c.$wrapper).width(b),c.orbitWidth=c.$element.width();if(f>c.$element.height())c.$element.add(c.$wrapper).height(f),c.orbitHeight=c.$element.height(),d=a(this).clone();c.numberSlides+=1});this.options.fluid&&(typeof this.options.fluid==="string"&&(d=a('<img src="http://placehold.it/'+
this.options.fluid+'" />')),c.$element.prepend(d),d.addClass("fluid-placeholder"),c.$element.add(c.$wrapper).css({width:"inherit"}),c.$element.add(c.$wrapper).css({height:"inherit"}),a(window).bind("resize",function(){c.orbitWidth=c.$element.width();c.orbitHeight=c.$element.height()}))},lock:function(){this.locked=!0},unlock:function(){this.locked=!1},updateOptionsIfOnlyOneSlide:function(){if(this.$slides.length===1)this.options.directionalNav=!1,this.options.timer=!1,this.options.bullets=!1},setupFirstSlide:function(){var a=
this;this.$slides.first().css({"z-index":3}).fadeIn(function(){a.$slides.css({display:"block"})})},startClock:function(){if(!this.options.timer)return!1;this.$timer.is(":hidden")?this.clock=setInterval(function(){this.$element.trigger("orbit.next")},this.options.advanceSpeed):(this.timerRunning=!0,this.$pause.removeClass("active"),this.clock=setInterval(this.rotateTimer,this.options.advanceSpeed/180))},rotateTimer:function(){var a="rotate("+this.degrees+"deg)";this.degrees+=2;this.$rotator.css({"-webkit-transform":a,
"-moz-transform":a,"-o-transform":a});this.degrees>180&&(this.$rotator.addClass("move"),this.$mask.addClass("move"));if(this.degrees>360)this.$rotator.removeClass("move"),this.$mask.removeClass("move"),this.degrees=0,this.$element.trigger("orbit.next")},stopClock:function(){if(this.options.timer)this.timerRunning=!1,clearInterval(this.clock),this.$pause.addClass("active");else return!1},setupTimer:function(){this.$timer=a(this.timerHTML);this.$wrapper.append(this.$timer);this.$rotator=this.$timer.find(".rotator");
this.$mask=this.$timer.find(".mask");this.$pause=this.$timer.find(".pause");this.$timer.click(this.clickTimer);this.options.startClockOnMouseOut&&(this.$wrapper.mouseleave(this.startTimerAfterMouseLeave),this.$wrapper.mouseenter(this.clearClockMouseLeaveTimer));this.options.pauseOnHover&&this.$wrapper.mouseenter(this.stopClock)},startTimerAfterMouseLeave:function(){var a=this;this.outTimer=setTimeout(function(){a.timerRunning||a.startClock()},this.options.startClockOnMouseOutAfter)},clearClockMouseLeaveTimer:function(){clearTimeout(this.outTimer)},
clickTimer:function(){this.timerRunning?this.stopClock():this.startClock()},setupCaptions:function(){this.$caption=a(this.captionHTML);this.$wrapper.append(this.$caption);this.setCaption()},setCaption:function(){var c=this.currentSlide().attr("data-caption"),d;if(!this.options.captions)return!1;if(c)switch(d=a(c).html(),this.$caption.attr("id",c).html(d),this.options.captionAnimation){case "none":this.$caption.show();break;case "fade":this.$caption.fadeIn(this.options.captionAnimationSpeed);break;
case "slideOpen":this.$caption.slideDown(this.options.captionAnimationSpeed)}else switch(this.options.captionAnimation){case "none":this.$caption.hide();break;case "fade":this.$caption.fadeOut(this.options.captionAnimationSpeed);break;case "slideOpen":this.$caption.slideUp(this.options.captionAnimationSpeed)}},setupDirectionalNav:function(){var a=this;this.$wrapper.append(this.directionalNavHTML);this.$wrapper.find(".left").click(function(){a.stopClock();a.$element.trigger("orbit.prev")});this.$wrapper.find(".right").click(function(){a.stopClock();
a.$element.trigger("orbit.next")})},setupBulletNav:function(){this.$bullets=a(this.bulletHTML);this.$wrapper.append(this.$bullets);this.$slides.each(this.addBullet);this.options.centerBullets&&this.$bullets.css("margin-left",-this.$bullets.width()/2)},addBullet:function(c,d){var b=a("<li>"+(c+1)+"</li>"),e,g=this;this.options.bulletThumbs&&(e=a(d).attr("data-thumb"))&&b.addClass("has-thumb").css({background:"url("+this.options.bulletThumbLocation+e+") no-repeat"});this.$bullets.append(b);b.data("index",
c);b.click(function(){g.stopClock();g.$element.trigger("orbit.goto",[b.data("index")])})},setActiveBullet:function(){if(this.options.bullets)this.$bullets.find("li").removeClass("active").eq(this.activeSlide).addClass("active");else return!1},resetAndUnlock:function(){this.$slides.eq(this.prevActiveSlide).css({"z-index":1});this.unlock();this.options.afterSlideChange.call(this,this.$slides.eq(this.prevActiveSlide),this.$slides.eq(this.activeSlide))},shift:function(a){var d=a;this.prevActiveSlide=
this.activeSlide;if(this.prevActiveSlide==d)return!1;if(this.$slides.length=="1")return!1;if(!this.locked){this.lock();if(a=="next"){if(this.activeSlide++,this.activeSlide==this.numberSlides)this.activeSlide=0}else if(a=="prev"){if(this.activeSlide--,this.activeSlide<0)this.activeSlide=this.numberSlides-1}else this.activeSlide=a,this.prevActiveSlide<this.activeSlide?d="next":this.prevActiveSlide>this.activeSlide&&(d="prev");this.setActiveBullet();this.$slides.eq(this.prevActiveSlide).css({"z-index":2});
this.options.animation=="fade"&&this.$slides.eq(this.activeSlide).css({opacity:0,"z-index":3}).animate({opacity:1},this.options.animationSpeed,this.resetAndUnlock);this.options.animation=="horizontal-slide"&&(d=="next"&&this.$slides.eq(this.activeSlide).css({left:this.orbitWidth,"z-index":3}).animate({left:0},this.options.animationSpeed,this.resetAndUnlock),d=="prev"&&this.$slides.eq(this.activeSlide).css({left:-this.orbitWidth,"z-index":3}).animate({left:0},this.options.animationSpeed,this.resetAndUnlock));
this.options.animation=="vertical-slide"&&(d=="prev"&&this.$slides.eq(this.activeSlide).css({top:this.orbitHeight,"z-index":3}).animate({top:0},this.options.animationSpeed,this.resetAndUnlock),d=="next"&&this.$slides.eq(this.activeSlide).css({top:-this.orbitHeight,"z-index":3}).animate({top:0},this.options.animationSpeed,this.resetAndUnlock));this.options.animation=="horizontal-push"&&(d=="next"&&(this.$slides.eq(this.activeSlide).css({left:this.orbitWidth,"z-index":3}).animate({left:0},this.options.animationSpeed,
this.resetAndUnlock),this.$slides.eq(this.prevActiveSlide).animate({left:-this.orbitWidth},this.options.animationSpeed)),d=="prev"&&(this.$slides.eq(this.activeSlide).css({left:-this.orbitWidth,"z-index":3}).animate({left:0},this.options.animationSpeed,this.resetAndUnlock),this.$slides.eq(this.prevActiveSlide).animate({left:this.orbitWidth},this.options.animationSpeed)));this.options.animation=="vertical-push"&&(d=="next"&&(this.$slides.eq(this.activeSlide).css({top:-this.orbitHeight,"z-index":3}).animate({top:0},
this.options.animationSpeed,this.resetAndUnlock),this.$slides.eq(this.prevActiveSlide).animate({top:this.orbitHeight},this.options.animationSpeed)),d=="prev"&&(this.$slides.eq(this.activeSlide).css({top:this.orbitHeight,"z-index":3}).animate({top:0},this.options.animationSpeed,this.resetAndUnlock),this.$slides.eq(this.prevActiveSlide).animate({top:-this.orbitHeight},this.options.animationSpeed)));this.setCaption()}}};a.fn.orbit=function(c){return this.each(function(){a.extend({},b).init(this,c)})}})(jQuery);
(function(a){function b(c,b){var e=a(c);e.bind("load.imageready",function(){b.apply(c,arguments);e.unbind("load.imageready")})}var c={};a.event.special.imageready={setup:function(a){c=a||c},add:function(d){var f=a(this),e;this.nodeType===1&&this.tagName.toLowerCase()==="img"&&this.src!==""&&(c.forceLoad?(e=f.attr("src"),f.attr("src",""),b(this,d.handler),f.attr("src",e)):this.complete||this.readyState===4?d.handler.apply(this,arguments):b(this,d.handler))},teardown:function(){a(this).unbind(".imageready")}}})(jQuery);
new function(a){a.fn.placeholder=function(b){var b=b||{},c=b.dataKey||"placeholderValue",d=b.attr||"placeholder",f=b.className||"placeholder",e=b.values||[],g=b.blockSubmit||!1,j=b.blankSubmit||!1,i=b.onSubmit||!1,h=b.value||"",k=b.cursor_position||0;return this.filter(":input").each(function(b){a.data(this,c,e[b]||a(this).attr(d))}).each(function(){a.trim(a(this).val())===""&&a(this).addClass(f).val(a.data(this,c))}).focus(function(){a.trim(a(this).val())===a.data(this,c)&&a(this).removeClass(f).val(h);
a.fn.setCursorPosition&&a(this).setCursorPosition(k)}).blur(function(){a.trim(a(this).val())===h&&a(this).addClass(f).val(a.data(this,c))}).each(function(d,b){g?new function(b){a(b.form).submit(function(){return a.trim(a(b).val())!=a.data(b,c)})}(b):j?new function(b){a(b.form).submit(function(){a.trim(a(b).val())==a.data(b,c)&&a(b).removeClass(f).val("");return!0})}(b):i&&new function(b){a(b.form).submit(i)}(b)})}}(jQuery);
jQuery(document).ready(function(a){function b(b){a("form.custom input:"+b).each(function(){var d=a('<span class="custom '+b+'"></span>');a(this).next("span.custom."+b).length===0&&(this.checked&&d.addClass("checked"),a(this).hide().after(d))})}b("checkbox");b("radio");a("form.custom select").each(function(){var b=a(this),d=b.next("div.custom.dropdown"),f=b.find("option"),e=0,g;d.length===0&&(d=a('<div class="custom dropdown"><a href="#" class="selector"></a><ul></ul></div>"'),f.each(function(){g=
a("<li>"+a(this).html()+"</li>");d.find("ul").append(g)}),d.prepend('<a href="#" class="current">'+f.first().html()+"</a>"),b.after(d),b.hide());f.each(function(b){this.selected&&(d.find("li").eq(b).addClass("selected"),d.find(".current").html(a(this).html()))});d.find("li").each(function(){d.addClass("open");a(this).outerWidth()>e&&(e=a(this).outerWidth());d.removeClass("open")});d.css("width",e+18+"px");d.find("ul").css("width",e+16+"px")})});
(function(a){function b(a){var b=a.prev()[0];b.checked=b.checked?!1:!0;a.toggleClass("checked")}function c(b){var c=b.prev(),e=c[0];a("input:radio[name="+c.attr("name")+"]").each(function(){a(this).next().removeClass("checked")});e.checked=e.checked?!1:!0;b.toggleClass("checked")}a("form.custom span.custom.checkbox").live("click",function(c){c.preventDefault();c.stopPropagation();b(a(this))});a("form.custom span.custom.radio").live("click",function(b){b.preventDefault();b.stopPropagation();c(a(this))});
a("form.custom label").live("click",function(d){var f=a("#"+a(this).attr("for"));f.length!==0&&(f.attr("type")==="checkbox"?(d.preventDefault(),d=a(this).find("span.custom.checkbox"),b(d)):f.attr("type")==="radio"&&(d.preventDefault(),d=a(this).find("span.custom.radio"),c(d)))});a("form.custom div.custom.dropdown a.current, form.custom div.custom.dropdown a.selector").live("click",function(b){var c=a(this).closest("div.custom.dropdown");b.preventDefault();c.toggleClass("open");c.hasClass("open")?
a(document).bind("click.customdropdown",function(){c.removeClass("open");a(document).unbind(".customdropdown")}):a(document).unbind(".customdropdown")});a("form.custom div.custom.dropdown li").live("click",function(b){var c=a(this),e=c.closest("div.custom.dropdown"),g=e.prev(),j=0;b.preventDefault();b.stopPropagation();c.closest("ul").find("li").removeClass("selected");c.addClass("selected");e.removeClass("open").find("a.current").html(c.html());c.closest("ul").find("li").each(function(a){c[0]==this&&
(j=a)});g[0].selectedIndex=j})})(jQuery);
(function(a,b,c){function d(a){var b={},d=/^jQuery\d+$/;c.each(a.attributes,function(a,c){if(c.specified&&!d.test(c.name))b[c.name]=c.value});return b}function f(){var a=c(this);a.val()===a.attr("placeholder")&&a.hasClass("placeholder")&&(a.data("placeholder-password")?a.hide().next().show().focus().attr("id",a.removeAttr("id").data("placeholder-id")):a.val("").removeClass("placeholder"))}function e(){var a,b=c(this),e=this.id;if(b.val()===""){if(b.is(":password")){if(!b.data("placeholder-textinput")){try{a=b.clone().attr({type:"text"})}catch(g){a=
c("<input>").attr(c.extend(d(this),{type:"text"}))}a.removeAttr("name").data("placeholder-password",!0).data("placeholder-id",e).bind("focus.placeholder",f);b.data("placeholder-textinput",a).data("placeholder-id",e).before(a)}b=b.removeAttr("id").hide().prev().attr("id",e).show()}b.addClass("placeholder").val(b.attr("placeholder"))}else b.removeClass("placeholder")}var g="placeholder"in b.createElement("input"),b="placeholder"in b.createElement("textarea");g&&b?(c.fn.placeholder=function(){return this},
c.fn.placeholder.input=c.fn.placeholder.textarea=!0):(c.fn.placeholder=function(){return this.filter((g?"textarea":":input")+"[placeholder]").bind("focus.placeholder",f).bind("blur.placeholder",e).trigger("blur.placeholder").end()},c.fn.placeholder.input=g,c.fn.placeholder.textarea=b,c(function(){c("form").bind("submit.placeholder",function(){var a=c(".placeholder",this).each(f);setTimeout(function(){a.each(e)},10)})}),c(a).bind("unload.placeholder",function(){c(".placeholder").val("")}))})(this,
document,jQuery);
